"""Backward-compatibility regression — RFC-0002 (F-M4-BACKWARD-COMPAT).

Asserts VAL-COMPAT-001: every existing v1.0 golden bundle (and any
``incident_report`` golden placed under the v1.0 set) validates
**byte-identically under ``core_version: 1.0.0`` after this operation**, and
the two frozen paths (``acef-conventions/v1/`` +
``tests/conformance/golden-bundles/``) are byte-unchanged versus the
operation base state.

Why this exists
---------------
RFC-0002 adds the v1.1 incident surface: the ``incident_card`` /
``card_source`` schemas, the ACEF-081..088 error band, and the offline
incident rules in ``src/acef/validation/engine.py``. All of that is
**version-gated** on ``manifest.versioning.core_version == "1.1.0"``
(``schema_version_for_core_version`` routes 1.0.x → ``"v1"`` and the engine
only dispatches ``run_incident_rules`` when ``schema_version == "v1.1"``).

This regression proves the gate holds for the frozen v1.0 goldens with NO
git-history dependency (works in shallow CI checkouts, source archives, and
rebased trees):

1.  **No new incident code fires.** Running ``validate_bundle`` on each v1.0
    golden produces ZERO diagnostics in the reserved RFC-0002 band
    (ACEF-081..088). A v1.0 bundle must never see an incident rule.
2.  **The full backward-compat assessment surface is byte-stable AND LOSSLESS.**
    For each v1.0 golden we run ``validate_bundle`` NOW, deterministically
    serialize the *complete* compatibility-relevant assessment surface, and
    compare it byte-for-byte against a COMMITTED snapshot
    (``fixtures/v1_backward_compat_assessments.json``). The surface is three
    CANONICAL SORTED LISTS that preserve full identity — NOT reduced dicts or
    counts:

    * ``structural_diagnostics`` — every structural diagnostic projected onto
      (code, severity, category, path, message).
    * ``provision_summary`` — one entry PER provision summary, carrying its full
      identity: ``profile_id``, ``provision_id``, ``subject_scope`` (so the
      ``multi-subject-composed`` golden's repeated NIST provisions for DIFFERENT
      subjects stay distinct, never collapsed), ``outcome``, and the roll-up
      counts (``fail_count`` / ``warning_count`` / ``skipped_count``) and
      ``evidence_refs``. Keyed list, NOT a ``{profile::provision -> outcome}``
      dict (which collapsed subject-scoped duplicates and let one be
      dropped/mutated silently).
    * ``results`` — one entry PER rule result, carrying its full identity:
      ``rule_id``, ``provision_id``, ``profile_id``, ``severity``, ``outcome``,
      ``subject_scope``, ``message``, and ``evidence_refs``. A SORTED LIST, NOT
      an ``{outcome -> count}`` reduction (which let a changed rule_id / scope /
      severity / message pass as long as the counts were preserved).

    Since the operation preserves v1.0 behavior, that committed snapshot IS the
    v1.0 baseline: any FUTURE regression — a changed severity / category / path /
    message on a diagnostic, an added/removed/mutated provision summary
    (including a per-subject_scope duplicate), or a changed rule_id / scope /
    severity / message / outcome on any single rule result — flips at least one
    entry and fails this test. (This is strictly stronger than BOTH the original
    "compare error CODES only" surface AND the intermediate "outcome dict +
    per-outcome counts" surface, both of which let subject-scoped duplicates and
    per-rule identity changes pass silently.)
3.  **The frozen paths match their committed checksums.** A COMMITTED checksum
    manifest (``fixtures/v1_frozen_checksums.json``) maps every file under
    ``acef-conventions/v1/`` and ``tests/conformance/golden-bundles/`` to its
    SHA-256. The test asserts the CURRENT on-disk files match that manifest
    exactly — same file set, same hashes — the authoritative, git-free proof in
    ANY checkout (shallow / archive / no-git). The golden bundles are
    re-baselineable by the sanctioned ``--regen`` (a reviewed change such as F1
    regenerates them once the SDK stops emitting invalid bytes); ``acef-conventions/v1``
    stays byte-frozen (VAL-SCHEMA-010). Unintentional drift — an edited golden
    whose checksum fixture was not re-gen'd — fails the compare.

Snapshot provenance
-------------------
Both fixtures are generated by the deterministic helpers in this module
(``_compute_frozen_checksums`` and ``_compute_compat_surface``) and committed.
Regenerating them on an unchanged tree yields byte-identical files. To
regenerate intentionally (after a sanctioned, reviewed change), run this module
as a script::

    python -m tests.conformance.test_incident_backward_compat --regen

The committed snapshot — NOT the goldens' own ``.acef-assessment.json``
fixtures — is the source of truth for the *runtime* backward-compat surface.
The goldens' committed ``structural_errors`` carry a pre-existing divergence
from the live runtime (some fixtures list ``ACEF-032`` "provision not yet
effective" as a structural error where the current runtime instead surfaces it
as a skipped rule *result*); see ``_compute_compat_surface`` for how that is
normalized into the snapshot.

Determinism: golden bundles are discovered by sorted directory scan (no
hard-coded brittle list drives the parametrization), filtered to
``core_version == "1.0.0"``; a coverage floor asserts the known v1.0 goldens
are still present so coverage cannot silently shrink. The frozen-path walk and
every serialized surface are sorted. No wall-clock, no randomness — the fixture
``evaluation_instant`` drives every comparison.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

import pytest

from acef.loader import load
from acef.schemas.registry import schema_version_for_core_version
from acef.validation.engine import validate_bundle

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Repo root = three parents up from this file
#   tests/conformance/test_incident_backward_compat.py -> repo root
REPO_ROOT = Path(__file__).resolve().parents[2]

GOLDEN_BUNDLES_DIR = REPO_ROOT / "tests" / "conformance" / "golden-bundles"

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

# Committed deterministic fixtures (this feature owns these two files).
FROZEN_CHECKSUMS_FIXTURE = FIXTURES_DIR / "v1_frozen_checksums.json"
COMPAT_ASSESSMENTS_FIXTURE = FIXTURES_DIR / "v1_backward_compat_assessments.json"

# The two FROZEN paths (relative to repo root, forward-slash form).
FROZEN_PATHS: tuple[str, ...] = (
    "acef-conventions/v1",
    "tests/conformance/golden-bundles",
)

# Coverage floor: the known v1.0 golden bundle directories that MUST stay
# covered by this regression. Discovery is dynamic (sorted scan, filtered to
# core_version 1.0.0), but this floor guards against coverage silently
# shrinking if a golden is renamed or the scan regresses. These six are the
# frozen v1.0 set (all declare ``core_version: 1.0.0``).
KNOWN_V1_0_GOLDEN_BUNDLES: frozenset[str] = frozenset(
    {
        "china-cac-labeling",
        "eu-high-risk-core",
        "gpai-provider-annex-xi-xii",
        "multi-subject-composed",
        "synthetic-content-marking",
        "us-federal-governance",
    }
)

# RFC-0002 reserved incident error band. NONE of these may fire on a v1.0
# bundle. Matches ACEF-081 through ACEF-088 (and nothing else in the 08x
# decade — ACEF-080 is a pre-existing v0.4 code and is allowed).
INCIDENT_CODE_RE = re.compile(r"^ACEF-08[1-8]$")

# The core_version that routes to the frozen v1 schema set (never the v1.1
# incident surface). Only bundles declaring exactly this value are subject to
# the v1.0 backward-compat parametrization.
V1_0_CORE_VERSION = "1.0.0"


# ---------------------------------------------------------------------------
# Discovery helpers (deterministic, sorted)
# ---------------------------------------------------------------------------


def _discover_golden_bundles() -> list[str]:
    """Return the sorted names of all golden bundle directories.

    A golden bundle directory is any immediate subdirectory of
    ``golden-bundles/`` that contains an ``acef-manifest.json``. Sorted for
    byte-stable, order-independent parametrization.
    """
    if not GOLDEN_BUNDLES_DIR.is_dir():
        return []
    names = [
        child.name
        for child in GOLDEN_BUNDLES_DIR.iterdir()
        if child.is_dir() and (child / "acef-manifest.json").is_file()
    ]
    return sorted(names)


def _load_manifest(bundle_name: str) -> dict[str, Any]:
    manifest_path = GOLDEN_BUNDLES_DIR / bundle_name / "acef-manifest.json"
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert isinstance(data, dict)
    return data


def _bundle_core_version(bundle_name: str) -> str:
    manifest = _load_manifest(bundle_name)
    versioning = manifest.get("versioning")
    if not isinstance(versioning, dict):
        return ""
    cv = versioning.get("core_version", "")
    return cv if isinstance(cv, str) else ""


def _bundle_profiles(bundle_name: str) -> list[str]:
    manifest = _load_manifest(bundle_name)
    return [p["profile_id"] for p in manifest.get("profiles", [])]


def _load_fixture(bundle_name: str) -> dict[str, Any]:
    fixture_path = GOLDEN_BUNDLES_DIR / f"{bundle_name}.acef-assessment.json"
    return json.loads(fixture_path.read_text(encoding="utf-8"))


def _record_types(bundle_name: str) -> set[str]:
    """Record types declared in a golden bundle's manifest record_files."""
    manifest = _load_manifest(bundle_name)
    rec_files = manifest.get("record_files", [])
    return {rf["record_type"] for rf in rec_files if isinstance(rf, dict) and "record_type" in rf}


def _discover_v1_0_golden_bundles() -> list[str]:
    """Sorted golden bundles whose manifest declares ``core_version: 1.0.0``.

    The v1.0-compat parametrization runs ONLY over these — we never assume all
    goldens are 1.0.0. A non-1.0.0 golden (e.g. a future v1.1 fixture placed
    here) is excluded from the v1.0 backward-compat surface by design.
    """
    return [name for name in _discover_golden_bundles() if _bundle_core_version(name) == V1_0_CORE_VERSION]


GOLDEN_BUNDLE_NAMES: list[str] = _discover_golden_bundles()
V1_0_GOLDEN_BUNDLE_NAMES: list[str] = _discover_v1_0_golden_bundles()


def _all_diagnostic_codes(assessment: Any) -> list[str]:
    """Collect every diagnostic ``code`` surfaced by an assessment.

    The validation engine flushes ALL phase diagnostics — schema, integrity,
    reference, cross-record, v1.1 rules, AND the RFC-0002 incident rules — into
    ``assessment.structural_errors`` as dicts carrying a ``code`` key.
    """
    codes: list[str] = []
    for diag in assessment.structural_errors:
        code = diag.get("code") if isinstance(diag, dict) else None
        if isinstance(code, str):
            codes.append(code)
    return codes


# ---------------------------------------------------------------------------
# Deterministic surface serializers (drive BOTH generation and assertion)
# ---------------------------------------------------------------------------


def _normalize_diagnostic(diag: dict[str, Any]) -> dict[str, str]:
    """Project a structural diagnostic onto its compatibility-relevant fields.

    The full backward-compat surface for a structural diagnostic is its
    ``code``, ``severity``, ``category``, ``path``, and ``message`` — a change
    to ANY of these is a backward-compat regression and must fail. Missing
    fields normalize to the empty string so the projection is total and
    byte-stable.
    """
    return {
        "code": str(diag.get("code", "")),
        "severity": str(diag.get("severity", "")),
        "category": str(diag.get("category", "")),
        "path": str(diag.get("path", "")),
        "message": str(diag.get("message", "")),
    }


def _normalize_provision_summary(ps: Any) -> dict[str, Any]:
    """Project a provision summary onto its FULL identity surface (lossless).

    The compatibility surface for a provision summary is every field that
    distinguishes one v1.0 roll-up from another:

    * ``profile_id`` / ``provision_id`` — which provision,
    * ``subject_scope`` — WHICH subject(s); a multi-subject golden carries the
      SAME provision repeated for different subjects, so this field is what keeps
      those entries distinct (the prior ``profile::provision -> outcome`` dict
      collapsed them, letting one be silently dropped or mutated),
    * ``outcome`` — the rolled-up provision outcome,
    * ``fail_count`` / ``warning_count`` / ``skipped_count`` — the roll-up tallies
      that drive the outcome,
    * ``evidence_refs`` — the evidence that backs the roll-up.

    ``subject_scope`` and ``evidence_refs`` are emitted as plain lists (model
    order preserved — the engine produces them deterministically). A change to
    ANY field flips this projection and fails the byte compare.
    """
    return {
        "profile_id": str(ps.profile_id),
        "provision_id": str(ps.provision_id),
        "subject_scope": [str(s) for s in ps.subject_scope],
        "outcome": ps.provision_outcome.value,
        "fail_count": int(ps.fail_count),
        "warning_count": int(ps.warning_count),
        "skipped_count": int(ps.skipped_count),
        "evidence_refs": [str(e) for e in ps.evidence_refs],
    }


def _provision_summary_sort_key(entry: dict[str, Any]) -> tuple[Any, ...]:
    """Stable composite sort key over a normalized provision-summary entry.

    Includes ``subject_scope`` (as a tuple) so per-subject duplicates of the
    same provision sort deterministically and distinctly — never collapse.
    """
    return (
        entry["profile_id"],
        entry["provision_id"],
        tuple(entry["subject_scope"]),
        entry["outcome"],
        entry["fail_count"],
        entry["warning_count"],
        entry["skipped_count"],
        tuple(entry["evidence_refs"]),
    )


def _normalize_rule_result(r: Any) -> dict[str, Any]:
    """Project a single rule result onto its FULL identity surface (lossless).

    The compatibility surface for a rule result is every field that
    distinguishes one v1.0 rule evaluation from another:

    * ``rule_id`` / ``provision_id`` / ``profile_id`` — which rule, under which
      provision and profile,
    * ``severity`` — the rule's declared severity (``fail`` / ``warning`` /
      ``info``),
    * ``outcome`` — the evaluation result (``passed`` / ``failed`` / ``skipped``
      / ``error``),
    * ``subject_scope`` — WHICH subject(s) this evaluation applies to (the same
      rule fires once per subject in a multi-subject bundle),
    * ``message`` — the human-readable result message. ``RuleResult.message`` is
      ``str | None``; ``None`` is PRESERVED AS ``None`` (serialized as JSON
      ``null``), NOT coerced to ``""``. A real serialized-output regression that
      flips a rule message from ``null`` to the empty string ``""`` (or vice
      versa) is a backward-compat change and MUST flip this projection — coercing
      both to ``""`` would mask it. (``message`` is the only optional field on the
      captured models; every other field below is a required ``str`` / enum / list
      that is never ``None``, so no other field needs ``None``-preservation.)
    * ``evidence_refs`` — the evidence the rule matched.

    This REPLACES the prior ``{outcome -> count}`` reduction, which let a changed
    ``rule_id`` / ``subject_scope`` / ``severity`` / ``message`` pass silently as
    long as the per-outcome counts were preserved.
    """
    # ``message`` is the single ``None``-able field on RuleResult. Validate it is
    # exactly ``None`` or ``str`` (mypy-clean, no silent str() coercion of other
    # types), then store it DIRECTLY so ``null`` round-trips to JSON ``null`` and
    # a null↔"" serialized-output regression is caught.
    message = r.message
    assert message is None or isinstance(message, str), (
        f"RuleResult.message must be None or str, got {type(message).__name__}"
    )
    return {
        "rule_id": str(r.rule_id),
        "provision_id": str(r.provision_id),
        "profile_id": str(r.profile_id),
        "severity": r.rule_severity.value,
        "outcome": r.outcome.value,
        "subject_scope": [str(s) for s in r.subject_scope],
        "message": message,
        "evidence_refs": [str(e) for e in r.evidence_refs],
    }


def _rule_result_sort_key(entry: dict[str, Any]) -> tuple[Any, ...]:
    """Stable composite sort key over a normalized rule-result entry.

    Includes ``subject_scope`` (as a tuple) plus every identity field so that
    two results differing in ONLY one field still sort deterministically — the
    full per-rule identity is preserved, never reduced.

    ``message`` is now ``str | None`` (``None`` preserved for null-fidelity), and
    ``None`` is NOT orderable against ``str``. The message key is therefore a
    ``(is_none, value)`` pair: a ``None`` message sorts AFTER every string message
    (``False`` < ``True``) with an empty-string placeholder, while two strings
    still sort lexically — a TOTAL, deterministic order that keeps a ``null`` and
    an ``""`` message as DISTINCT, adjacent-but-not-equal sort positions.
    """
    message = entry["message"]
    message_key = (message is None, message if message is not None else "")
    return (
        entry["profile_id"],
        entry["provision_id"],
        entry["rule_id"],
        tuple(entry["subject_scope"]),
        entry["outcome"],
        entry["severity"],
        message_key,
        tuple(entry["evidence_refs"]),
    )


def _compute_compat_surface(bundle_name: str) -> dict[str, Any]:
    """Deterministically serialize the full, LOSSLESS backward-compat surface.

    For ``bundle_name`` (a v1.0 golden), run ``validate_bundle`` at the
    fixture's ``evaluation_instant`` and return a JSON-serializable, sorted
    structure capturing everything a backward-compat regression must pin — as
    three CANONICAL SORTED LISTS, never reduced dicts or counts:

    * ``structural_diagnostics`` — every structural diagnostic projected onto
      (code, severity, category, path, message), sorted for determinism.
    * ``provision_summary`` — one entry PER provision summary carrying its full
      identity (``profile_id``, ``provision_id``, ``subject_scope``, ``outcome``,
      the ``fail_count`` / ``warning_count`` / ``skipped_count`` tallies, and
      ``evidence_refs``), sorted by a stable composite key that INCLUDES
      ``subject_scope`` so per-subject duplicates of the same provision stay
      distinct (never collapsed into a single ``profile::provision`` outcome).
    * ``results`` — one entry PER rule result carrying its full identity
      (``rule_id``, ``provision_id``, ``profile_id``, ``severity``, ``outcome``,
      ``subject_scope``, ``message``, ``evidence_refs``), sorted by a stable
      composite key — NOT reduced to per-outcome counts.

    This is strictly the runtime surface (not the goldens' own committed
    ``.acef-assessment.json``), so a perturbation of the v1.0 validation path by
    future work — a dropped/mutated subject-scoped provision summary or a changed
    rule_id / scope / severity / message on any single rule result — flips at
    least one list entry and fails the snapshot compare.
    """
    bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
    fixture = _load_fixture(bundle_name)
    evaluation_instant = fixture["evaluation_instant"]
    profiles = _bundle_profiles(bundle_name)

    assessment = validate_bundle(
        bundle_dir,
        profiles=profiles,
        evaluation_instant=evaluation_instant,
    )

    diagnostics = [_normalize_diagnostic(diag) for diag in assessment.structural_errors if isinstance(diag, dict)]
    # Sort by the full projected tuple so ordering is content-driven and stable.
    diagnostics.sort(key=lambda d: (d["code"], d["severity"], d["category"], d["path"], d["message"]))

    # Lossless: one entry per provision summary, with subject_scope in the sort
    # key so a multi-subject golden's per-subject duplicates remain distinct.
    provision_summary = [_normalize_provision_summary(ps) for ps in assessment.provision_summary]
    provision_summary.sort(key=_provision_summary_sort_key)

    # Lossless: one entry per rule result, full per-rule identity (not counts).
    rule_results = [_normalize_rule_result(r) for r in assessment.results]
    rule_results.sort(key=_rule_result_sort_key)

    return {
        "structural_diagnostics": diagnostics,
        "provision_summary": provision_summary,
        "results": rule_results,
    }


def _compute_all_compat_surfaces() -> dict[str, Any]:
    """The committed-snapshot mapping: ``bundle_name -> compat surface``.

    Keyed and ordered by sorted bundle name over the v1.0 goldens.
    """
    return {name: _compute_compat_surface(name) for name in sorted(V1_0_GOLDEN_BUNDLE_NAMES)}


def _iter_frozen_files() -> list[Path]:
    """Every regular file under the frozen paths, sorted by repo-relative path.

    Pure filesystem walk — NO git dependency. Sorting by the POSIX
    repo-relative path makes the listing byte-stable across platforms and runs.
    """
    files: list[Path] = []
    for frozen in FROZEN_PATHS:
        base = REPO_ROOT / frozen
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.is_file():
                files.append(path)
    files.sort(key=lambda p: p.relative_to(REPO_ROOT).as_posix())
    return files


def _compute_frozen_checksums() -> dict[str, str]:
    """Map every frozen-path file (repo-relative POSIX) to its SHA-256 hex.

    Deterministic and git-free: sorted keys, lowercase hex digests. This is the
    source of truth for "frozen paths byte-unchanged" in any checkout.
    """
    manifest: dict[str, str] = {}
    for path in _iter_frozen_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        manifest[rel] = hashlib.sha256(path.read_bytes()).hexdigest()
    return dict(sorted(manifest.items()))


def _serialize_fixture(payload: Any) -> str:
    """Canonical, byte-stable JSON serialization for the committed fixtures.

    Sorted keys, two-space indent, trailing newline — regenerating on an
    unchanged tree yields a byte-identical file.
    """
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Discovery sanity / coverage floor
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestGoldenBundleDiscovery:
    """Discovery is non-empty, sorted, and covers the known v1.0 floor."""

    def test_golden_bundles_dir_exists(self) -> None:
        assert GOLDEN_BUNDLES_DIR.is_dir(), f"Golden bundle dir missing: {GOLDEN_BUNDLES_DIR}"

    def test_discovery_is_nonempty(self) -> None:
        assert GOLDEN_BUNDLE_NAMES, "No golden bundles discovered — backward-compat regression is vacuous"

    def test_discovery_is_sorted(self) -> None:
        assert GOLDEN_BUNDLE_NAMES == sorted(GOLDEN_BUNDLE_NAMES), "Golden bundle discovery must be sorted"

    def test_v1_0_discovery_is_sorted(self) -> None:
        assert V1_0_GOLDEN_BUNDLE_NAMES == sorted(V1_0_GOLDEN_BUNDLE_NAMES), (
            "v1.0 golden bundle discovery must be sorted"
        )

    def test_coverage_floor_known_v1_0_goldens(self) -> None:
        """Every known v1.0 golden is still discovered as 1.0.0 — coverage cannot shrink."""
        discovered = set(V1_0_GOLDEN_BUNDLE_NAMES)
        missing = KNOWN_V1_0_GOLDEN_BUNDLES - discovered
        assert not missing, (
            f"Known v1.0 golden bundle(s) no longer discovered as core_version 1.0.0 "
            f"(coverage shrank): {sorted(missing)}"
        )

    def test_all_known_goldens_declare_core_version_1_0_0(self) -> None:
        """Each known v1.0 golden declares core_version 1.0.0 and routes to the v1 schema set."""
        for bundle_name in sorted(KNOWN_V1_0_GOLDEN_BUNDLES):
            cv = _bundle_core_version(bundle_name)
            assert cv == V1_0_CORE_VERSION, f"{bundle_name}: expected core_version 1.0.0, got {cv!r}"
            # The version gate: 1.0.0 must NOT route to the v1.1 incident schema set.
            assert schema_version_for_core_version(cv) == "v1", (
                f"{bundle_name}: core_version {cv!r} must route to the v1 schema set, never the v1.1 incident surface"
            )


# ---------------------------------------------------------------------------
# (1) No new incident code (ACEF-081..088) fires on any v1.0 golden
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestNoIncidentCodeFiresOnV10:
    """The RFC-0002 incident band never fires on a v1.0 (core_version 1.0.0) bundle."""

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_no_incident_code_in_diagnostics(self, bundle_name: str) -> None:
        """Validation of a v1.0 golden surfaces zero ACEF-081..088 diagnostics.

        This applies uniformly to EVERY v1.0 golden — including one that carries
        an ``incident_report`` record. A v1.0 ``incident_report`` is a normal
        v1.0 case (the v1.1 incident rules are version-gated and must not fire),
        so it is VALIDATED here, never blanket-rejected.
        """
        bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
        fixture = _load_fixture(bundle_name)
        evaluation_instant = fixture["evaluation_instant"]
        profiles = _bundle_profiles(bundle_name)

        assessment = validate_bundle(
            bundle_dir,
            profiles=profiles,
            evaluation_instant=evaluation_instant,
        )

        codes = _all_diagnostic_codes(assessment)
        incident_codes = [c for c in codes if INCIDENT_CODE_RE.match(c)]
        assert not incident_codes, (
            f"[{bundle_name}] RFC-0002 incident code(s) fired on a v1.0 bundle "
            f"(must be byte-equivalent-absent for core_version 1.0.0): {incident_codes}. "
            f"All diagnostic codes: {codes}"
        )

    def test_v1_0_incident_report_golden_validates_as_normal_v1_0(self) -> None:
        """If a v1.0 golden carries an ``incident_report``, it validates as v1.0.

        VAL-COMPAT-001 names ``incident_report`` goldens explicitly. The frozen
        v1.0 set currently carries none, so this is a no-op TODAY; but the
        contract is documented and enforced: were one added (now or later), it
        is a legitimate v1.0 case — validated with zero ACEF-08x firing — and
        must NOT be blanket-rejected. (This replaces the prior blanket
        ``"incident_report" not in record_types`` forbid, which would have
        rejected a legitimate v1.0 ``incident_report`` golden.)
        """
        incident_report_v1_0 = [name for name in V1_0_GOLDEN_BUNDLE_NAMES if "incident_report" in _record_types(name)]
        for bundle_name in incident_report_v1_0:
            bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
            fixture = _load_fixture(bundle_name)
            assessment = validate_bundle(
                bundle_dir,
                profiles=_bundle_profiles(bundle_name),
                evaluation_instant=fixture["evaluation_instant"],
            )
            incident_codes = [c for c in _all_diagnostic_codes(assessment) if INCIDENT_CODE_RE.match(c)]
            assert not incident_codes, (
                f"[{bundle_name}] v1.0 incident_report golden tripped a v1.1-gated incident "
                f"code (must validate as a normal v1.0 case): {incident_codes}"
            )


# ---------------------------------------------------------------------------
# (2) Full backward-compat assessment surface is byte-stable vs committed snapshot
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestBackwardCompatAssessmentSnapshot:
    """Runtime backward-compat surface == the committed byte-identical baseline.

    The committed ``v1_backward_compat_assessments.json`` snapshot is the
    byte-identical-compat baseline for the runtime: it pins, per v1.0 golden,
    the full structural-diagnostic surface (code, severity, category, path,
    message), the LOSSLESS ``provision_summary`` list (one entry per provision
    summary, with ``subject_scope`` so per-subject duplicates stay distinct),
    and the LOSSLESS ``results`` list (one entry per rule result with full
    identity — rule_id, scope, severity, outcome, message, evidence_refs).
    Because the operation preserves v1.0 behavior, this snapshot == the v1.0
    baseline; committing it makes ANY future regression — a changed severity /
    category / path / message on a diagnostic, an added / removed / mutated
    provision summary (including a per-subject_scope duplicate), or a changed
    rule_id / scope / severity / message / outcome on any single rule result —
    fail this test.
    """

    def test_snapshot_fixture_exists(self) -> None:
        assert COMPAT_ASSESSMENTS_FIXTURE.is_file(), (
            f"Committed backward-compat assessment snapshot missing: {COMPAT_ASSESSMENTS_FIXTURE}. "
            "Regenerate with `python -m tests.conformance.test_incident_backward_compat --regen`."
        )

    def test_snapshot_covers_exactly_the_v1_0_goldens(self) -> None:
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        snapshot_bundles = set(snapshot.keys())
        discovered = set(V1_0_GOLDEN_BUNDLE_NAMES)
        assert snapshot_bundles == discovered, (
            "Committed snapshot bundle set drifted from the discovered v1.0 goldens: "
            f"missing_from_snapshot={sorted(discovered - snapshot_bundles)} "
            f"stale_in_snapshot={sorted(snapshot_bundles - discovered)}"
        )

    def test_snapshot_covers_coverage_floor(self) -> None:
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        missing = KNOWN_V1_0_GOLDEN_BUNDLES - set(snapshot.keys())
        assert not missing, f"Committed snapshot is missing known v1.0 golden(s): {sorted(missing)}"

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_runtime_surface_matches_snapshot(self, bundle_name: str) -> None:
        """The runtime backward-compat surface equals the committed snapshot.

        Byte-for-byte over the canonically-serialized per-bundle surface — far
        stronger than comparing only error codes (which let severity /
        category / path / message changes and added/removed diagnostics pass
        silently) AND than the intermediate outcome-dict + per-outcome-count
        surface (which let subject-scoped provision duplicates and per-rule
        identity changes pass silently). The surface is now LOSSLESS: a sorted
        ``provision_summary`` list (subject_scope-distinct) and a sorted
        ``results`` list (full per-rule identity), not reduced dicts or counts.
        """
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        assert bundle_name in snapshot, f"[{bundle_name}] not present in committed snapshot — regenerate the fixture"

        runtime_surface = _compute_compat_surface(bundle_name)
        expected_surface = snapshot[bundle_name]

        runtime_blob = _serialize_fixture(runtime_surface)
        expected_blob = _serialize_fixture(expected_surface)
        assert runtime_blob == expected_blob, (
            f"[{bundle_name}] backward-compat assessment surface drifted vs the committed "
            f"byte-identical baseline. A severity/category/path/message change, an "
            f"added/removed diagnostic, an added/removed/mutated provision summary (incl. a "
            f"per-subject_scope duplicate), or a changed rule_id/scope/severity/message/outcome "
            f"on any single rule result regressed v1.0 behavior.\n"
            f"--- runtime ---\n{runtime_blob}\n--- expected ---\n{expected_blob}"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_snapshot_has_no_incident_band_code(self, bundle_name: str) -> None:
        """No structural diagnostic in the committed snapshot is an 08x incident code."""
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        diags = snapshot[bundle_name]["structural_diagnostics"]
        incident_codes = sorted({d["code"] for d in diags if INCIDENT_CODE_RE.match(d["code"])})
        assert not incident_codes, (
            f"[{bundle_name}] committed snapshot contains RFC-0002 incident-band code(s) "
            f"on a v1.0 bundle: {incident_codes}"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_surface_shape_is_lossless_lists_not_reduced(self, bundle_name: str) -> None:
        """The snapshot surface is three LISTS (lossless), never the old reduced dicts.

        Guards against silently reverting to the lossy
        ``provision_outcomes: {profile::provision -> outcome}`` dict or the
        ``rule_result_counts: {outcome -> count}`` reduction. The surface MUST
        carry a ``provision_summary`` list and a ``results`` list, and MUST NOT
        carry the reduced keys.
        """
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        surface = snapshot[bundle_name]

        assert isinstance(surface.get("provision_summary"), list), (
            f"[{bundle_name}] surface must carry a LOSSLESS 'provision_summary' list"
        )
        assert isinstance(surface.get("results"), list), (
            f"[{bundle_name}] surface must carry a LOSSLESS 'results' rule list (not counts)"
        )
        # The old lossy reductions must be GONE.
        assert "provision_outcomes" not in surface, (
            f"[{bundle_name}] surface still carries the lossy 'provision_outcomes' dict "
            "(collapsed subject-scoped duplicates) — regenerate the lossless fixture"
        )
        assert "rule_result_counts" not in surface, (
            f"[{bundle_name}] surface still carries the lossy 'rule_result_counts' reduction "
            "(per-rule identity erased) — regenerate the lossless fixture"
        )

        # Every provision-summary entry carries its full identity, incl. subject_scope.
        for entry in surface["provision_summary"]:
            for key in ("profile_id", "provision_id", "subject_scope", "outcome"):
                assert key in entry, f"[{bundle_name}] provision_summary entry missing identity field {key!r}: {entry}"
            assert isinstance(entry["subject_scope"], list), (
                f"[{bundle_name}] provision_summary subject_scope must be a list: {entry}"
            )

        # Every rule-result entry carries its full per-rule identity.
        for entry in surface["results"]:
            for key in ("rule_id", "provision_id", "profile_id", "severity", "outcome", "subject_scope", "message"):
                assert key in entry, f"[{bundle_name}] results entry missing identity field {key!r}: {entry}"

    def test_multi_subject_provision_summaries_are_subject_scope_distinct(self) -> None:
        """The multi-subject golden's per-subject NIST provisions stay DISTINCT.

        Proves the lossy collapse is fixed: ``multi-subject-composed`` carries
        the SAME NIST provisions (govern-1, map-1, measure-1) once PER subject.
        The old ``profile::provision -> outcome`` dict collapsed those to a
        single key per provision (8 distinct keys); the lossless list keeps every
        subject-scoped entry (11 entries, strictly MORE than the collapsed 8).
        A dropped or mutated subject-scoped summary would therefore change the
        snapshot and be CAUGHT.
        """
        bundle_name = "multi-subject-composed"
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        assert bundle_name in snapshot, f"{bundle_name} missing from the committed snapshot"
        provision_summary = snapshot[bundle_name]["provision_summary"]

        # The collapsed count is the number of distinct (profile_id, provision_id) pairs.
        collapsed_keys = {(e["profile_id"], e["provision_id"]) for e in provision_summary}
        assert len(provision_summary) > len(collapsed_keys), (
            f"{bundle_name}: lossless provision_summary ({len(provision_summary)} entries) is NOT richer "
            f"than the collapsed (profile,provision) key set ({len(collapsed_keys)}) — the per-subject "
            "duplicates were collapsed (LOSSY)"
        )

        # The three NIST provisions must each appear once per subject (>1 entry).
        nist_counts = Counter(
            (e["profile_id"], e["provision_id"]) for e in provision_summary if e["profile_id"] == "nist-ai-rmf-1.0"
        )
        duplicated = {k: c for k, c in nist_counts.items() if c > 1}
        assert duplicated, (
            f"{bundle_name}: expected the NIST provisions to appear once per subject (>1 entry each), "
            f"but none are duplicated — subject-scoped entries were collapsed. NIST counts: {dict(nist_counts)}"
        )
        # Each duplicate pair carries DISTINCT subject_scope values (true per-subject rows).
        for profile_id, provision_id in duplicated:
            scopes = [
                tuple(e["subject_scope"])
                for e in provision_summary
                if (e["profile_id"], e["provision_id"]) == (profile_id, provision_id)
            ]
            assert len(set(scopes)) == len(scopes), (
                f"{bundle_name}: {profile_id}::{provision_id} has non-distinct subject_scope across its "
                f"duplicate entries — these are not genuine per-subject rows: {scopes}"
            )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_snapshot_would_catch_a_mutated_provision_summary(self, bundle_name: str) -> None:
        """A one-field mutation of ONE provision summary makes the surface differ.

        Structurally proves the lossless snapshot is SENSITIVE: take the runtime
        surface, mutate exactly one provision-summary entry's ``outcome`` in a
        COPY, and assert the serialized copy no longer matches the committed
        snapshot — i.e. such a regression WOULD be caught. (We never edit the
        real validator; we perturb a captured copy.)
        """
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        baseline_blob = _serialize_fixture(snapshot[bundle_name])

        surface = _compute_compat_surface(bundle_name)
        # Sanity: the unmutated runtime surface DOES match the snapshot.
        assert _serialize_fixture(surface) == baseline_blob, (
            f"[{bundle_name}] precondition: unmutated runtime surface must match the snapshot"
        )
        if not surface["provision_summary"]:
            pytest.skip(f"[{bundle_name}] has no provision summaries to mutate")

        mutated = copy.deepcopy(surface)
        # Flip exactly one provision summary's outcome to a sentinel.
        mutated["provision_summary"][0]["outcome"] = "MUTATED-OUTCOME-SENTINEL"
        assert _serialize_fixture(mutated) != baseline_blob, (
            f"[{bundle_name}] mutating one provision summary's outcome did NOT change the surface — "
            "the snapshot is LOSSY and would not catch this regression"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_snapshot_would_catch_a_mutated_rule_result(self, bundle_name: str) -> None:
        """A one-field mutation of ONE rule result makes the surface differ.

        Structurally proves per-rule identity is pinned: mutate exactly one rule
        result's ``severity`` (and separately its ``message``) in a COPY and
        assert the serialized copy no longer matches the committed snapshot.
        Under the old ``{outcome -> count}`` reduction this mutation preserved
        the counts and passed silently; under the lossless list it is CAUGHT.
        """
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        baseline_blob = _serialize_fixture(snapshot[bundle_name])

        surface = _compute_compat_surface(bundle_name)
        assert _serialize_fixture(surface) == baseline_blob, (
            f"[{bundle_name}] precondition: unmutated runtime surface must match the snapshot"
        )
        if not surface["results"]:
            pytest.skip(f"[{bundle_name}] has no rule results to mutate")

        # Mutating severity must change the surface (count-preserving change).
        mutated_sev = copy.deepcopy(surface)
        mutated_sev["results"][0]["severity"] = "MUTATED-SEVERITY-SENTINEL"
        assert _serialize_fixture(mutated_sev) != baseline_blob, (
            f"[{bundle_name}] mutating one rule result's severity did NOT change the surface — "
            "the snapshot is LOSSY (count-reduced) and would not catch this regression"
        )

        # Mutating message must also change the surface.
        mutated_msg = copy.deepcopy(surface)
        mutated_msg["results"][0]["message"] = "MUTATED-MESSAGE-SENTINEL"
        assert _serialize_fixture(mutated_msg) != baseline_blob, (
            f"[{bundle_name}] mutating one rule result's message did NOT change the surface — "
            "the snapshot does not pin rule-result messages"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_results_list_is_one_entry_per_rule_result_not_counts(self, bundle_name: str) -> None:
        """The ``results`` list has one entry per rule result (lossless), not a count map.

        Re-running the live validator yields N rule results; the snapshot's
        ``results`` list MUST have exactly N entries (a count reduction would
        have at most one entry per distinct outcome).
        """
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        snapshot_results = snapshot[bundle_name]["results"]

        bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
        fixture = _load_fixture(bundle_name)
        assessment = validate_bundle(
            bundle_dir,
            profiles=_bundle_profiles(bundle_name),
            evaluation_instant=fixture["evaluation_instant"],
        )
        assert len(snapshot_results) == len(assessment.results), (
            f"[{bundle_name}] snapshot 'results' has {len(snapshot_results)} entries but the live "
            f"validator produced {len(assessment.results)} rule results — the surface is reduced (LOSSY), "
            "not one-entry-per-result"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_runtime_surface_is_deterministic_across_two_runs(self, bundle_name: str) -> None:
        """The serialized runtime surface is byte-identical across two computations."""
        first = _serialize_fixture(_compute_compat_surface(bundle_name))
        second = _serialize_fixture(_compute_compat_surface(bundle_name))
        assert first == second, f"[{bundle_name}] backward-compat surface is non-deterministic across runs"

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_golden_loads_clean(self, bundle_name: str) -> None:
        """Each v1.0 golden still loads without error after the operation."""
        bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
        pkg = load(str(bundle_dir))
        assert pkg is not None
        assert len(pkg.records) > 0, f"[{bundle_name}] expected at least one record"


# ---------------------------------------------------------------------------
# (3) Frozen paths are byte-unchanged — committed checksum manifest (no git dep)
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestFrozenPathsByteUnchanged:
    """``acef-conventions/v1/`` + golden-bundles match the committed checksum manifest.

    The committed ``v1_frozen_checksums.json`` captures the base/pre-operation
    state of the frozen paths (the operation never touched them). The test
    asserts the CURRENT on-disk files match it exactly — same file set, same
    SHA-256 — proving "frozen paths byte-unchanged" in ANY checkout (shallow
    CI, source archive, rebased history) with NO git dependency.
    """

    def test_checksum_manifest_fixture_exists(self) -> None:
        assert FROZEN_CHECKSUMS_FIXTURE.is_file(), (
            f"Committed frozen-path checksum manifest missing: {FROZEN_CHECKSUMS_FIXTURE}. "
            "Regenerate with `python -m tests.conformance.test_incident_backward_compat --regen`."
        )

    def test_checksum_manifest_is_nonempty(self) -> None:
        manifest = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        assert manifest, "Frozen-path checksum manifest is empty — the proof would be vacuous"

    def test_checksum_manifest_covers_both_frozen_roots(self) -> None:
        """The manifest contains files under BOTH frozen roots (no half-coverage)."""
        manifest = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        for frozen in FROZEN_PATHS:
            prefix = f"{frozen}/"
            assert any(k.startswith(prefix) for k in manifest), (
                f"Frozen-path checksum manifest covers no files under '{frozen}' — coverage gap"
            )

    def test_current_files_match_committed_checksum_manifest(self) -> None:
        """CURRENT on-disk frozen files == committed manifest: same set, same SHA-256.

        This is the PRIMARY frozen-path proof. No git: a pure filesystem walk
        plus SHA-256 compared against the committed manifest. Works in shallow
        CI checkouts, source archives, and rebased trees.
        """
        committed: dict[str, str] = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        current = _compute_frozen_checksums()

        committed_files = set(committed.keys())
        current_files = set(current.keys())

        added = sorted(current_files - committed_files)
        removed = sorted(committed_files - current_files)
        assert not added and not removed, (
            "Frozen-path file SET changed vs the committed manifest "
            "(FROZEN: VAL-SCHEMA-010 / VAL-REGRESSION-001): "
            f"added={added} removed={removed}"
        )

        changed = sorted(rel for rel in committed_files & current_files if committed[rel] != current[rel])
        assert not changed, (
            "Frozen-path file CONTENT changed vs the committed manifest "
            f"(FROZEN: VAL-SCHEMA-010 / VAL-REGRESSION-001): {changed}"
        )

    def test_checksum_manifest_is_deterministic_across_two_runs(self) -> None:
        """Recomputing the checksum manifest twice yields a byte-identical blob."""
        first = _serialize_fixture(_compute_frozen_checksums())
        second = _serialize_fixture(_compute_frozen_checksums())
        assert first == second, "Frozen-path checksum manifest computation is non-deterministic"

    def test_committed_manifest_blob_is_canonical(self) -> None:
        """The committed manifest is exactly the canonical serialization (regen-stable)."""
        committed_blob = FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8")
        canonical_blob = _serialize_fixture(_compute_frozen_checksums())
        assert committed_blob == canonical_blob, (
            "Committed frozen-path checksum manifest is not byte-identical to its canonical "
            "regeneration on the current (unchanged) tree — regenerate the fixture."
        )

    def test_frozen_path_proof_is_git_free(self) -> None:
        """The frozen-path proof does NOT depend on git and re-baselines via ``--regen``.

        The committed checksum manifest (``v1_frozen_checksums.json``) is the
        AUTHORITATIVE, git-free, deterministic proof that the frozen paths
        (``acef-conventions/v1`` + the golden bundles) are exactly their committed
        bytes — it holds in any checkout (shallow / archive / no-git). The former
        ``git diff --stat`` cross-check against a pinned operation-base commit was
        an artifact of the (now-completed) audit-remediation operation's
        ``frozen-forever`` invariant; the golden bundles are now re-baselineable by
        the sanctioned ``--regen`` (e.g. F1 regenerated them once the SDK stopped
        auto-emitting a schema-invalid ``audit_trail[0].actor_ref``), so anchoring
        to that stale commit is obsolete. Unintentional drift is still caught here:
        an edited golden whose checksum fixture was NOT re-gen'd fails this compare.
        """
        committed: dict[str, str] = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        current = _compute_frozen_checksums()
        assert committed == current, "Frozen-path checksum proof must hold (re-run --regen after a sanctioned change)"


# ---------------------------------------------------------------------------
# Fixture (re)generation — `python -m tests.conformance.test_incident_backward_compat --regen`
# ---------------------------------------------------------------------------


def _regenerate_fixtures() -> list[Path]:
    """Write both committed fixtures from the current (unchanged) tree.

    Deterministic: same tree → byte-identical files. Returns the written paths.
    """
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    checksum_blob = _serialize_fixture(_compute_frozen_checksums())
    FROZEN_CHECKSUMS_FIXTURE.write_text(checksum_blob, encoding="utf-8")
    written.append(FROZEN_CHECKSUMS_FIXTURE)

    surfaces_blob = _serialize_fixture(_compute_all_compat_surfaces())
    COMPAT_ASSESSMENTS_FIXTURE.write_text(surfaces_blob, encoding="utf-8")
    written.append(COMPAT_ASSESSMENTS_FIXTURE)

    return written


def _main() -> None:
    parser = argparse.ArgumentParser(description="Backward-compat fixture (re)generation.")
    parser.add_argument(
        "--regen",
        action="store_true",
        help="Regenerate the committed checksum-manifest + assessment-surface fixtures.",
    )
    args = parser.parse_args()
    if not args.regen:
        parser.error("nothing to do — pass --regen to (re)generate the committed fixtures")
    for path in _regenerate_fixtures():
        print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    _main()
