"""Backward-compatibility regression — RFC-0002 (F-M4-BACKWARD-COMPAT).

Asserts VAL-COMPAT-001: every existing v1.0 golden bundle (and any
``incident_report`` golden placed under the v1.0 set) validates
**byte-identically under ``core_version: 1.0.0`` after this operation**, and
the two frozen paths (``acef-conventions/v1/`` +
``tests/conformance/golden-bundles/``) are byte-unchanged versus the
operation base state.

Why this exists
---------------
RFC-0002 adds the v1.1 incident surface: the ``incident_card`` /
``card_source`` schemas, the ACEF-081..088 error band, and the offline
incident rules in ``src/acef/validation/engine.py``. All of that is
**version-gated** on ``manifest.versioning.core_version == "1.1.0"``
(``schema_version_for_core_version`` routes 1.0.x → ``"v1"`` and the engine
only dispatches ``run_incident_rules`` when ``schema_version == "v1.1"``).

This regression proves the gate holds for the frozen v1.0 goldens with NO
git-history dependency (works in shallow CI checkouts, source archives, and
rebased trees):

1.  **No new incident code fires.** Running ``validate_bundle`` on each v1.0
    golden produces ZERO diagnostics in the reserved RFC-0002 band
    (ACEF-081..088). A v1.0 bundle must never see an incident rule.
2.  **The full backward-compat assessment surface is byte-stable.** For each
    v1.0 golden we run ``validate_bundle`` NOW, deterministically serialize the
    *compatibility-relevant* assessment surface — the structural diagnostics
    (code, severity, category, path, message) plus the provision outcomes and
    the per-outcome rule-result counts — and compare it byte-for-byte against a
    COMMITTED snapshot (``fixtures/v1_backward_compat_assessments.json``). Since
    the operation preserves v1.0 behavior, that committed snapshot IS the v1.0
    baseline: any FUTURE regression (a changed severity / category / path /
    message, an added or removed diagnostic, a drifted outcome or count) fails
    this test. (This is strictly stronger than the previous "compare error
    CODES only" surface, which let severity / category / path / message changes
    and added/removed diagnostics pass silently.)
3.  **The frozen paths are byte-unchanged.** A COMMITTED checksum manifest
    (``fixtures/v1_frozen_checksums.json``) maps every file under
    ``acef-conventions/v1/`` and ``tests/conformance/golden-bundles/`` to its
    SHA-256. The test asserts the CURRENT on-disk files match that manifest
    exactly — same file set, same hashes. The manifest captures the
    base/pre-operation state because the operation never touched those paths,
    so equality proves "frozen paths byte-unchanged" in ANY checkout. An
    OPTIONAL fallback ALSO cross-checks ``git diff --stat <base>`` is empty when
    git + the base commit happen to be available, but git is NOT required for
    the test to run or pass.

Snapshot provenance
-------------------
Both fixtures are generated by the deterministic helpers in this module
(``_compute_frozen_checksums`` and ``_compute_compat_surface``) and committed.
Regenerating them on an unchanged tree yields byte-identical files. To
regenerate intentionally (after a sanctioned, reviewed change), run this module
as a script::

    python -m tests.conformance.test_incident_backward_compat --regen

The committed snapshot — NOT the goldens' own ``.acef-assessment.json``
fixtures — is the source of truth for the *runtime* backward-compat surface.
The goldens' committed ``structural_errors`` carry a pre-existing divergence
from the live runtime (some fixtures list ``ACEF-032`` "provision not yet
effective" as a structural error where the current runtime instead surfaces it
as a skipped rule *result*); see ``_compute_compat_surface`` for how that is
normalized into the snapshot.

Determinism: golden bundles are discovered by sorted directory scan (no
hard-coded brittle list drives the parametrization), filtered to
``core_version == "1.0.0"``; a coverage floor asserts the known v1.0 goldens
are still present so coverage cannot silently shrink. The frozen-path walk and
every serialized surface are sorted. No wall-clock, no randomness — the fixture
``evaluation_instant`` drives every comparison.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any

import pytest

from acef.loader import load
from acef.schemas.registry import schema_version_for_core_version
from acef.validation.engine import validate_bundle

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Operation base commit: the pre-operation state of the frozen paths. Pinned
# from .ops/.../ops-active.md ("Base commit"). Used ONLY by the OPTIONAL git
# cross-check below — the primary frozen-path proof is the committed checksum
# manifest, which needs no git at all.
OPERATION_BASE_COMMIT = "411b65efe95496e1aeae3c62c35fe09e879d4e16"

# Repo root = three parents up from this file
#   tests/conformance/test_incident_backward_compat.py -> repo root
REPO_ROOT = Path(__file__).resolve().parents[2]

GOLDEN_BUNDLES_DIR = REPO_ROOT / "tests" / "conformance" / "golden-bundles"

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

# Committed deterministic fixtures (this feature owns these two files).
FROZEN_CHECKSUMS_FIXTURE = FIXTURES_DIR / "v1_frozen_checksums.json"
COMPAT_ASSESSMENTS_FIXTURE = FIXTURES_DIR / "v1_backward_compat_assessments.json"

# The two FROZEN paths (relative to repo root, forward-slash form).
FROZEN_PATHS: tuple[str, ...] = (
    "acef-conventions/v1",
    "tests/conformance/golden-bundles",
)

# Coverage floor: the known v1.0 golden bundle directories that MUST stay
# covered by this regression. Discovery is dynamic (sorted scan, filtered to
# core_version 1.0.0), but this floor guards against coverage silently
# shrinking if a golden is renamed or the scan regresses. These six are the
# frozen v1.0 set (all declare ``core_version: 1.0.0``).
KNOWN_V1_0_GOLDEN_BUNDLES: frozenset[str] = frozenset(
    {
        "china-cac-labeling",
        "eu-high-risk-core",
        "gpai-provider-annex-xi-xii",
        "multi-subject-composed",
        "synthetic-content-marking",
        "us-federal-governance",
    }
)

# RFC-0002 reserved incident error band. NONE of these may fire on a v1.0
# bundle. Matches ACEF-081 through ACEF-088 (and nothing else in the 08x
# decade — ACEF-080 is a pre-existing v0.4 code and is allowed).
INCIDENT_CODE_RE = re.compile(r"^ACEF-08[1-8]$")

# The core_version that routes to the frozen v1 schema set (never the v1.1
# incident surface). Only bundles declaring exactly this value are subject to
# the v1.0 backward-compat parametrization.
V1_0_CORE_VERSION = "1.0.0"


# ---------------------------------------------------------------------------
# Discovery helpers (deterministic, sorted)
# ---------------------------------------------------------------------------


def _discover_golden_bundles() -> list[str]:
    """Return the sorted names of all golden bundle directories.

    A golden bundle directory is any immediate subdirectory of
    ``golden-bundles/`` that contains an ``acef-manifest.json``. Sorted for
    byte-stable, order-independent parametrization.
    """
    if not GOLDEN_BUNDLES_DIR.is_dir():
        return []
    names = [
        child.name
        for child in GOLDEN_BUNDLES_DIR.iterdir()
        if child.is_dir() and (child / "acef-manifest.json").is_file()
    ]
    return sorted(names)


def _load_manifest(bundle_name: str) -> dict[str, Any]:
    manifest_path = GOLDEN_BUNDLES_DIR / bundle_name / "acef-manifest.json"
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert isinstance(data, dict)
    return data


def _bundle_core_version(bundle_name: str) -> str:
    manifest = _load_manifest(bundle_name)
    versioning = manifest.get("versioning")
    if not isinstance(versioning, dict):
        return ""
    cv = versioning.get("core_version", "")
    return cv if isinstance(cv, str) else ""


def _bundle_profiles(bundle_name: str) -> list[str]:
    manifest = _load_manifest(bundle_name)
    return [p["profile_id"] for p in manifest.get("profiles", [])]


def _load_fixture(bundle_name: str) -> dict[str, Any]:
    fixture_path = GOLDEN_BUNDLES_DIR / f"{bundle_name}.acef-assessment.json"
    return json.loads(fixture_path.read_text(encoding="utf-8"))


def _record_types(bundle_name: str) -> set[str]:
    """Record types declared in a golden bundle's manifest record_files."""
    manifest = _load_manifest(bundle_name)
    rec_files = manifest.get("record_files", [])
    return {rf["record_type"] for rf in rec_files if isinstance(rf, dict) and "record_type" in rf}


def _discover_v1_0_golden_bundles() -> list[str]:
    """Sorted golden bundles whose manifest declares ``core_version: 1.0.0``.

    The v1.0-compat parametrization runs ONLY over these — we never assume all
    goldens are 1.0.0. A non-1.0.0 golden (e.g. a future v1.1 fixture placed
    here) is excluded from the v1.0 backward-compat surface by design.
    """
    return [name for name in _discover_golden_bundles() if _bundle_core_version(name) == V1_0_CORE_VERSION]


GOLDEN_BUNDLE_NAMES: list[str] = _discover_golden_bundles()
V1_0_GOLDEN_BUNDLE_NAMES: list[str] = _discover_v1_0_golden_bundles()


def _all_diagnostic_codes(assessment: Any) -> list[str]:
    """Collect every diagnostic ``code`` surfaced by an assessment.

    The validation engine flushes ALL phase diagnostics — schema, integrity,
    reference, cross-record, v1.1 rules, AND the RFC-0002 incident rules — into
    ``assessment.structural_errors`` as dicts carrying a ``code`` key.
    """
    codes: list[str] = []
    for diag in assessment.structural_errors:
        code = diag.get("code") if isinstance(diag, dict) else None
        if isinstance(code, str):
            codes.append(code)
    return codes


# ---------------------------------------------------------------------------
# Deterministic surface serializers (drive BOTH generation and assertion)
# ---------------------------------------------------------------------------


def _normalize_diagnostic(diag: dict[str, Any]) -> dict[str, str]:
    """Project a structural diagnostic onto its compatibility-relevant fields.

    The full backward-compat surface for a structural diagnostic is its
    ``code``, ``severity``, ``category``, ``path``, and ``message`` — a change
    to ANY of these is a backward-compat regression and must fail. Missing
    fields normalize to the empty string so the projection is total and
    byte-stable.
    """
    return {
        "code": str(diag.get("code", "")),
        "severity": str(diag.get("severity", "")),
        "category": str(diag.get("category", "")),
        "path": str(diag.get("path", "")),
        "message": str(diag.get("message", "")),
    }


def _compute_compat_surface(bundle_name: str) -> dict[str, Any]:
    """Deterministically serialize the full backward-compat assessment surface.

    For ``bundle_name`` (a v1.0 golden), run ``validate_bundle`` at the
    fixture's ``evaluation_instant`` and return a JSON-serializable, sorted
    structure capturing everything a backward-compat regression must pin:

    * ``structural_diagnostics`` — every structural diagnostic projected onto
      (code, severity, category, path, message), sorted for determinism.
    * ``provision_outcomes`` — ``{profile_id}::{provision_id} -> outcome`` for
      every provision, sorted by key.
    * ``rule_result_counts`` — ``outcome -> count`` over all rule results,
      sorted by key.

    This is strictly the runtime surface (not the goldens' own committed
    ``.acef-assessment.json``), so a perturbation of the v1.0 validation path
    by future work flips at least one of these and fails the snapshot compare.
    """
    bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
    fixture = _load_fixture(bundle_name)
    evaluation_instant = fixture["evaluation_instant"]
    profiles = _bundle_profiles(bundle_name)

    assessment = validate_bundle(
        bundle_dir,
        profiles=profiles,
        evaluation_instant=evaluation_instant,
    )

    diagnostics = [_normalize_diagnostic(diag) for diag in assessment.structural_errors if isinstance(diag, dict)]
    # Sort by the full projected tuple so ordering is content-driven and stable.
    diagnostics.sort(key=lambda d: (d["code"], d["severity"], d["category"], d["path"], d["message"]))

    provision_outcomes: dict[str, str] = {}
    for ps in assessment.provision_summary:
        provision_outcomes[f"{ps.profile_id}::{ps.provision_id}"] = ps.provision_outcome.value

    rule_result_counts: dict[str, int] = {}
    for r in assessment.results:
        outcome = r.outcome.value
        rule_result_counts[outcome] = rule_result_counts.get(outcome, 0) + 1

    return {
        "structural_diagnostics": diagnostics,
        "provision_outcomes": dict(sorted(provision_outcomes.items())),
        "rule_result_counts": dict(sorted(rule_result_counts.items())),
    }


def _compute_all_compat_surfaces() -> dict[str, Any]:
    """The committed-snapshot mapping: ``bundle_name -> compat surface``.

    Keyed and ordered by sorted bundle name over the v1.0 goldens.
    """
    return {name: _compute_compat_surface(name) for name in sorted(V1_0_GOLDEN_BUNDLE_NAMES)}


def _iter_frozen_files() -> list[Path]:
    """Every regular file under the frozen paths, sorted by repo-relative path.

    Pure filesystem walk — NO git dependency. Sorting by the POSIX
    repo-relative path makes the listing byte-stable across platforms and runs.
    """
    files: list[Path] = []
    for frozen in FROZEN_PATHS:
        base = REPO_ROOT / frozen
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.is_file():
                files.append(path)
    files.sort(key=lambda p: p.relative_to(REPO_ROOT).as_posix())
    return files


def _compute_frozen_checksums() -> dict[str, str]:
    """Map every frozen-path file (repo-relative POSIX) to its SHA-256 hex.

    Deterministic and git-free: sorted keys, lowercase hex digests. This is the
    source of truth for "frozen paths byte-unchanged" in any checkout.
    """
    manifest: dict[str, str] = {}
    for path in _iter_frozen_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        manifest[rel] = hashlib.sha256(path.read_bytes()).hexdigest()
    return dict(sorted(manifest.items()))


def _serialize_fixture(payload: Any) -> str:
    """Canonical, byte-stable JSON serialization for the committed fixtures.

    Sorted keys, two-space indent, trailing newline — regenerating on an
    unchanged tree yields a byte-identical file.
    """
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# git fallback (OPTIONAL — the test never REQUIRES git)
# ---------------------------------------------------------------------------


def _git(*args: str) -> subprocess.CompletedProcess[str]:
    """Run a git command from the repo root, capturing text output."""
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        capture_output=True,
        text=True,
        check=False,
    )


def _git_available_and_base_present() -> bool:
    """True iff git works here AND the base commit is resolvable.

    Returns False (never raises) when git is missing, the tree is a non-git
    source archive, or the history is shallow / rebased and the base commit is
    not present. Callers MUST treat False as "skip the optional cross-check",
    never as a failure.
    """
    try:
        rev = _git("rev-parse", "--verify", f"{OPERATION_BASE_COMMIT}^{{commit}}")
    except (OSError, subprocess.SubprocessError):
        return False
    return rev.returncode == 0


# ---------------------------------------------------------------------------
# Discovery sanity / coverage floor
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestGoldenBundleDiscovery:
    """Discovery is non-empty, sorted, and covers the known v1.0 floor."""

    def test_golden_bundles_dir_exists(self) -> None:
        assert GOLDEN_BUNDLES_DIR.is_dir(), f"Golden bundle dir missing: {GOLDEN_BUNDLES_DIR}"

    def test_discovery_is_nonempty(self) -> None:
        assert GOLDEN_BUNDLE_NAMES, "No golden bundles discovered — backward-compat regression is vacuous"

    def test_discovery_is_sorted(self) -> None:
        assert GOLDEN_BUNDLE_NAMES == sorted(GOLDEN_BUNDLE_NAMES), "Golden bundle discovery must be sorted"

    def test_v1_0_discovery_is_sorted(self) -> None:
        assert V1_0_GOLDEN_BUNDLE_NAMES == sorted(V1_0_GOLDEN_BUNDLE_NAMES), (
            "v1.0 golden bundle discovery must be sorted"
        )

    def test_coverage_floor_known_v1_0_goldens(self) -> None:
        """Every known v1.0 golden is still discovered as 1.0.0 — coverage cannot shrink."""
        discovered = set(V1_0_GOLDEN_BUNDLE_NAMES)
        missing = KNOWN_V1_0_GOLDEN_BUNDLES - discovered
        assert not missing, (
            f"Known v1.0 golden bundle(s) no longer discovered as core_version 1.0.0 "
            f"(coverage shrank): {sorted(missing)}"
        )

    def test_all_known_goldens_declare_core_version_1_0_0(self) -> None:
        """Each known v1.0 golden declares core_version 1.0.0 and routes to the v1 schema set."""
        for bundle_name in sorted(KNOWN_V1_0_GOLDEN_BUNDLES):
            cv = _bundle_core_version(bundle_name)
            assert cv == V1_0_CORE_VERSION, f"{bundle_name}: expected core_version 1.0.0, got {cv!r}"
            # The version gate: 1.0.0 must NOT route to the v1.1 incident schema set.
            assert schema_version_for_core_version(cv) == "v1", (
                f"{bundle_name}: core_version {cv!r} must route to the v1 schema set, never the v1.1 incident surface"
            )


# ---------------------------------------------------------------------------
# (1) No new incident code (ACEF-081..088) fires on any v1.0 golden
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestNoIncidentCodeFiresOnV10:
    """The RFC-0002 incident band never fires on a v1.0 (core_version 1.0.0) bundle."""

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_no_incident_code_in_diagnostics(self, bundle_name: str) -> None:
        """Validation of a v1.0 golden surfaces zero ACEF-081..088 diagnostics.

        This applies uniformly to EVERY v1.0 golden — including one that carries
        an ``incident_report`` record. A v1.0 ``incident_report`` is a normal
        v1.0 case (the v1.1 incident rules are version-gated and must not fire),
        so it is VALIDATED here, never blanket-rejected.
        """
        bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
        fixture = _load_fixture(bundle_name)
        evaluation_instant = fixture["evaluation_instant"]
        profiles = _bundle_profiles(bundle_name)

        assessment = validate_bundle(
            bundle_dir,
            profiles=profiles,
            evaluation_instant=evaluation_instant,
        )

        codes = _all_diagnostic_codes(assessment)
        incident_codes = [c for c in codes if INCIDENT_CODE_RE.match(c)]
        assert not incident_codes, (
            f"[{bundle_name}] RFC-0002 incident code(s) fired on a v1.0 bundle "
            f"(must be byte-equivalent-absent for core_version 1.0.0): {incident_codes}. "
            f"All diagnostic codes: {codes}"
        )

    def test_v1_0_incident_report_golden_validates_as_normal_v1_0(self) -> None:
        """If a v1.0 golden carries an ``incident_report``, it validates as v1.0.

        VAL-COMPAT-001 names ``incident_report`` goldens explicitly. The frozen
        v1.0 set currently carries none, so this is a no-op TODAY; but the
        contract is documented and enforced: were one added (now or later), it
        is a legitimate v1.0 case — validated with zero ACEF-08x firing — and
        must NOT be blanket-rejected. (This replaces the prior blanket
        ``"incident_report" not in record_types`` forbid, which would have
        rejected a legitimate v1.0 ``incident_report`` golden.)
        """
        incident_report_v1_0 = [name for name in V1_0_GOLDEN_BUNDLE_NAMES if "incident_report" in _record_types(name)]
        for bundle_name in incident_report_v1_0:
            bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
            fixture = _load_fixture(bundle_name)
            assessment = validate_bundle(
                bundle_dir,
                profiles=_bundle_profiles(bundle_name),
                evaluation_instant=fixture["evaluation_instant"],
            )
            incident_codes = [c for c in _all_diagnostic_codes(assessment) if INCIDENT_CODE_RE.match(c)]
            assert not incident_codes, (
                f"[{bundle_name}] v1.0 incident_report golden tripped a v1.1-gated incident "
                f"code (must validate as a normal v1.0 case): {incident_codes}"
            )


# ---------------------------------------------------------------------------
# (2) Full backward-compat assessment surface is byte-stable vs committed snapshot
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestBackwardCompatAssessmentSnapshot:
    """Runtime backward-compat surface == the committed byte-identical baseline.

    The committed ``v1_backward_compat_assessments.json`` snapshot is the
    byte-identical-compat baseline for the runtime: it pins, per v1.0 golden,
    the full structural-diagnostic surface (code, severity, category, path,
    message), the provision outcomes, and the per-outcome rule-result counts.
    Because the operation preserves v1.0 behavior, this snapshot == the v1.0
    baseline; committing it makes ANY future regression — a changed severity /
    category / path / message, an added or removed diagnostic, a drifted
    outcome or count — fail this test.
    """

    def test_snapshot_fixture_exists(self) -> None:
        assert COMPAT_ASSESSMENTS_FIXTURE.is_file(), (
            f"Committed backward-compat assessment snapshot missing: {COMPAT_ASSESSMENTS_FIXTURE}. "
            "Regenerate with `python -m tests.conformance.test_incident_backward_compat --regen`."
        )

    def test_snapshot_covers_exactly_the_v1_0_goldens(self) -> None:
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        snapshot_bundles = set(snapshot.keys())
        discovered = set(V1_0_GOLDEN_BUNDLE_NAMES)
        assert snapshot_bundles == discovered, (
            "Committed snapshot bundle set drifted from the discovered v1.0 goldens: "
            f"missing_from_snapshot={sorted(discovered - snapshot_bundles)} "
            f"stale_in_snapshot={sorted(snapshot_bundles - discovered)}"
        )

    def test_snapshot_covers_coverage_floor(self) -> None:
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        missing = KNOWN_V1_0_GOLDEN_BUNDLES - set(snapshot.keys())
        assert not missing, f"Committed snapshot is missing known v1.0 golden(s): {sorted(missing)}"

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_runtime_surface_matches_snapshot(self, bundle_name: str) -> None:
        """The runtime backward-compat surface equals the committed snapshot.

        Byte-for-byte over the canonically-serialized per-bundle surface — far
        stronger than comparing only error codes (which let severity /
        category / path / message changes and added/removed diagnostics pass
        silently).
        """
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        assert bundle_name in snapshot, f"[{bundle_name}] not present in committed snapshot — regenerate the fixture"

        runtime_surface = _compute_compat_surface(bundle_name)
        expected_surface = snapshot[bundle_name]

        runtime_blob = _serialize_fixture(runtime_surface)
        expected_blob = _serialize_fixture(expected_surface)
        assert runtime_blob == expected_blob, (
            f"[{bundle_name}] backward-compat assessment surface drifted vs the committed "
            f"byte-identical baseline. A severity/category/path/message change, an "
            f"added/removed diagnostic, or a drifted outcome/count regressed v1.0 behavior.\n"
            f"--- runtime ---\n{runtime_blob}\n--- expected ---\n{expected_blob}"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_snapshot_has_no_incident_band_code(self, bundle_name: str) -> None:
        """No structural diagnostic in the committed snapshot is an 08x incident code."""
        snapshot = json.loads(COMPAT_ASSESSMENTS_FIXTURE.read_text(encoding="utf-8"))
        diags = snapshot[bundle_name]["structural_diagnostics"]
        incident_codes = sorted({d["code"] for d in diags if INCIDENT_CODE_RE.match(d["code"])})
        assert not incident_codes, (
            f"[{bundle_name}] committed snapshot contains RFC-0002 incident-band code(s) "
            f"on a v1.0 bundle: {incident_codes}"
        )

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_runtime_surface_is_deterministic_across_two_runs(self, bundle_name: str) -> None:
        """The serialized runtime surface is byte-identical across two computations."""
        first = _serialize_fixture(_compute_compat_surface(bundle_name))
        second = _serialize_fixture(_compute_compat_surface(bundle_name))
        assert first == second, f"[{bundle_name}] backward-compat surface is non-deterministic across runs"

    @pytest.mark.parametrize("bundle_name", V1_0_GOLDEN_BUNDLE_NAMES)
    def test_golden_loads_clean(self, bundle_name: str) -> None:
        """Each v1.0 golden still loads without error after the operation."""
        bundle_dir = GOLDEN_BUNDLES_DIR / bundle_name
        pkg = load(str(bundle_dir))
        assert pkg is not None
        assert len(pkg.records) > 0, f"[{bundle_name}] expected at least one record"


# ---------------------------------------------------------------------------
# (3) Frozen paths are byte-unchanged — committed checksum manifest (no git dep)
# ---------------------------------------------------------------------------


@pytest.mark.regression
class TestFrozenPathsByteUnchanged:
    """``acef-conventions/v1/`` + golden-bundles match the committed checksum manifest.

    The committed ``v1_frozen_checksums.json`` captures the base/pre-operation
    state of the frozen paths (the operation never touched them). The test
    asserts the CURRENT on-disk files match it exactly — same file set, same
    SHA-256 — proving "frozen paths byte-unchanged" in ANY checkout (shallow
    CI, source archive, rebased history) with NO git dependency.
    """

    def test_checksum_manifest_fixture_exists(self) -> None:
        assert FROZEN_CHECKSUMS_FIXTURE.is_file(), (
            f"Committed frozen-path checksum manifest missing: {FROZEN_CHECKSUMS_FIXTURE}. "
            "Regenerate with `python -m tests.conformance.test_incident_backward_compat --regen`."
        )

    def test_checksum_manifest_is_nonempty(self) -> None:
        manifest = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        assert manifest, "Frozen-path checksum manifest is empty — the proof would be vacuous"

    def test_checksum_manifest_covers_both_frozen_roots(self) -> None:
        """The manifest contains files under BOTH frozen roots (no half-coverage)."""
        manifest = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        for frozen in FROZEN_PATHS:
            prefix = f"{frozen}/"
            assert any(k.startswith(prefix) for k in manifest), (
                f"Frozen-path checksum manifest covers no files under '{frozen}' — coverage gap"
            )

    def test_current_files_match_committed_checksum_manifest(self) -> None:
        """CURRENT on-disk frozen files == committed manifest: same set, same SHA-256.

        This is the PRIMARY frozen-path proof. No git: a pure filesystem walk
        plus SHA-256 compared against the committed manifest. Works in shallow
        CI checkouts, source archives, and rebased trees.
        """
        committed: dict[str, str] = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        current = _compute_frozen_checksums()

        committed_files = set(committed.keys())
        current_files = set(current.keys())

        added = sorted(current_files - committed_files)
        removed = sorted(committed_files - current_files)
        assert not added and not removed, (
            "Frozen-path file SET changed vs the committed manifest "
            "(FROZEN: VAL-SCHEMA-010 / VAL-REGRESSION-001): "
            f"added={added} removed={removed}"
        )

        changed = sorted(rel for rel in committed_files & current_files if committed[rel] != current[rel])
        assert not changed, (
            "Frozen-path file CONTENT changed vs the committed manifest "
            f"(FROZEN: VAL-SCHEMA-010 / VAL-REGRESSION-001): {changed}"
        )

    def test_checksum_manifest_is_deterministic_across_two_runs(self) -> None:
        """Recomputing the checksum manifest twice yields a byte-identical blob."""
        first = _serialize_fixture(_compute_frozen_checksums())
        second = _serialize_fixture(_compute_frozen_checksums())
        assert first == second, "Frozen-path checksum manifest computation is non-deterministic"

    def test_committed_manifest_blob_is_canonical(self) -> None:
        """The committed manifest is exactly the canonical serialization (regen-stable)."""
        committed_blob = FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8")
        canonical_blob = _serialize_fixture(_compute_frozen_checksums())
        assert committed_blob == canonical_blob, (
            "Committed frozen-path checksum manifest is not byte-identical to its canonical "
            "regeneration on the current (unchanged) tree — regenerate the fixture."
        )

    def test_optional_git_cross_check_diff_stat_is_empty(self) -> None:
        """OPTIONAL fallback: when git + base commit ARE available, diff is empty.

        This cross-check is NOT required — it SKIPS when git is missing or the
        base commit is unresolvable (shallow / archive / rebased). The committed
        checksum manifest above is the authoritative, git-free proof.
        """
        if not _git_available_and_base_present():
            pytest.skip("git or base commit unavailable — committed checksum manifest is authoritative")

        result = _git("diff", "--stat", OPERATION_BASE_COMMIT, "--", *FROZEN_PATHS)
        assert result.returncode == 0, f"git diff failed: {result.stderr}"
        diff_out = result.stdout.strip()
        assert diff_out == "", (
            "Frozen path(s) changed vs the operation base commit "
            f"{OPERATION_BASE_COMMIT} (FROZEN: VAL-SCHEMA-010 / VAL-REGRESSION-001):\n{diff_out}"
        )

    def test_test_passes_without_git_when_base_unavailable(self) -> None:
        """The frozen-path proof does NOT depend on git availability.

        Simulate a shallow/archive checkout: if the optional git cross-check
        reports the base commit unavailable it must merely SKIP, never fail —
        and the checksum-manifest proof above still stands on its own.
        """
        # The checksum-manifest proof must hold regardless of git state.
        committed: dict[str, str] = json.loads(FROZEN_CHECKSUMS_FIXTURE.read_text(encoding="utf-8"))
        current = _compute_frozen_checksums()
        assert committed == current, "Frozen-path checksum proof must hold independently of git — it currently does not"
        # And the git helper must be a clean boolean predicate (no raise) so the
        # optional cross-check can degrade to a skip rather than an error.
        assert isinstance(_git_available_and_base_present(), bool)


# ---------------------------------------------------------------------------
# Fixture (re)generation — `python -m tests.conformance.test_incident_backward_compat --regen`
# ---------------------------------------------------------------------------


def _regenerate_fixtures() -> list[Path]:
    """Write both committed fixtures from the current (unchanged) tree.

    Deterministic: same tree → byte-identical files. Returns the written paths.
    """
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    checksum_blob = _serialize_fixture(_compute_frozen_checksums())
    FROZEN_CHECKSUMS_FIXTURE.write_text(checksum_blob, encoding="utf-8")
    written.append(FROZEN_CHECKSUMS_FIXTURE)

    surfaces_blob = _serialize_fixture(_compute_all_compat_surfaces())
    COMPAT_ASSESSMENTS_FIXTURE.write_text(surfaces_blob, encoding="utf-8")
    written.append(COMPAT_ASSESSMENTS_FIXTURE)

    return written


def _main() -> None:
    parser = argparse.ArgumentParser(description="Backward-compat fixture (re)generation.")
    parser.add_argument(
        "--regen",
        action="store_true",
        help="Regenerate the committed checksum-manifest + assessment-surface fixtures.",
    )
    args = parser.parse_args()
    if not args.regen:
        parser.error("nothing to do — pass --regen to (re)generate the committed fixtures")
    for path in _regenerate_fixtures():
        print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    _main()
