"""Independent drift oracle for the golden bundles (PhD-review finding 36).

The golden bundles are generated by the SAME SDK that validates them, and the
golden suite recomputes expectations from co-located fixtures — so a bug that is
SYMMETRIC across build and validate (e.g. a shared canonicalization quirk) is
invisible to that loop. This test pins each golden's **bundle digest** (the spec
§3.1.1 canonical identity: sha256 of the RFC 8785-canonical ``content-hashes.json``)
to a value frozen in ``golden-bundle-digests.json`` and recomputes it with **stdlib
hashlib only** — not the SDK canonicalizer — so canonicalization/hashing drift that
the self-referential suite would miss is caught against the frozen pin.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

_CONFORMANCE = Path(__file__).resolve().parent
_GOLDEN_DIR = _CONFORMANCE / "golden-bundles"
_PINS = json.loads((_CONFORMANCE / "golden-bundle-digests.json").read_text(encoding="utf-8"))
_GOLDENS = sorted(k for k in _PINS if not k.startswith("_"))


def _independent_bundle_digest(bundle: Path) -> str:
    """Bundle digest computed with ONLY stdlib hashlib over the on-disk canonical
    ``content-hashes.json`` bytes — no SDK code on the hashing path."""
    raw = (bundle / "hashes" / "content-hashes.json").read_bytes()
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def test_every_pinned_golden_exists() -> None:
    for name in _GOLDENS:
        assert (_GOLDEN_DIR / name / "hashes" / "content-hashes.json").exists(), f"pinned golden {name!r} is missing"
    # And every golden on disk is pinned (no silent un-oracled golden).
    on_disk = {p.parent.parent.name for p in _GOLDEN_DIR.glob("*/hashes/content-hashes.json")}
    assert on_disk == set(_GOLDENS), f"golden set drifted from the pin file: {on_disk ^ set(_GOLDENS)}"


@pytest.mark.parametrize("name", _GOLDENS)
def test_golden_bundle_digest_matches_frozen_pin(name: str) -> None:
    got = _independent_bundle_digest(_GOLDEN_DIR / name)
    assert got == _PINS[name], (
        f"{name}: bundle digest drifted from the frozen oracle\n  pinned: {_PINS[name]}\n  now:    {got}\n"
        "A mismatch means the bundle identity (spec §3.1.1) changed — do NOT update the pin to go green."
    )


@pytest.mark.parametrize("name", _GOLDENS)
def test_sdk_digest_agrees_with_independent_digest(name: str) -> None:
    """Cross-check: the SDK's canonicalize()+sha256 path computes the SAME digest
    as the stdlib-only path (the on-disk content-hashes.json is RFC 8785-canonical,
    so SDK canonicalize is a no-op). A divergence here localizes drift to the SDK
    canonicalizer rather than the stored bytes."""
    from acef.integrity import canonicalize, sha256_hex

    raw = (_GOLDEN_DIR / name / "hashes" / "content-hashes.json").read_bytes()
    sdk_digest = "sha256:" + sha256_hex(canonicalize(json.loads(raw)))
    assert sdk_digest == _PINS[name], f"{name}: SDK canonicalize/hash diverged from the frozen pin"
