"""Public ``acef.validate()`` must detect archive tampering — no load→export healing.

Finding loader-roundtrip-4 / VAL-FIX-LOADER-004 (root cause): the public
``acef.validate(<.tar.gz>)`` API resolved an archive input by ``load(path)`` →
``Package.export(tmp)`` → ``validate_bundle(tmp)``. That round-trip REGENERATES
``hashes/content-hashes.json`` and ``hashes/merkle-tree.json`` from the loaded
records, SILENTLY HEALING any tampering (a stripped Merkle tree, a content-hash
mismatch) before the integrity verifier ever ran. SDK callers therefore never
received the FATAL integrity verdict (ACEF-011 / ACEF-010) for a tampered
archive — the public API masked the defect even though the CLI workaround
(commit 3e2a9d7) handled it.

These tests call the LIBRARY ``acef.validate`` directly (NOT the CLI) and assert
the integrity verdict is surfaced for a raw-tampered archive, while a healthy
archive and directory inputs stay clean / unchanged.

RED proof (before the root fix): ``acef.validate(<archive: merkle removed>)``
returns an AssessmentBundle whose ``structural_errors`` contains NO ACEF-011 at
``/hashes/merkle-tree.json`` (the stripped file was regenerated by the
load→export round-trip), and ``acef.validate(<content-hash-mismatch archive>)``
contains NO ACEF-010 (the recomputed hashes matched the tampered bytes). After
the fix both are PRESENT and FATAL.
"""

from __future__ import annotations

import json
import tarfile
from pathlib import Path

import acef
from acef.package import Package


def _build_raw_archive(src_dir: Path, out: Path, *, skip: set[str] | None = None) -> None:
    """Pack ``src_dir`` into a raw ``.tar.gz`` at ``out``, preserving the on-disk
    file set EXACTLY (optionally omitting members named in ``skip``).

    Deliberately does NOT go through ``Package.export``: that regenerates
    ``hashes/content-hashes.json`` / ``hashes/merkle-tree.json`` from the loaded
    records, which would heal any tampering. To prove ``validate`` detects a
    tampered archive we ship the tampered bytes verbatim, nested under the bundle
    root exactly like a real archive.
    """
    skip = skip or set()
    with tarfile.open(str(out), "w:gz") as tar:
        for path in sorted(src_dir.rglob("*")):
            inner = path.relative_to(src_dir).as_posix()
            if inner in skip:
                continue
            arcname = path.relative_to(src_dir.parent).as_posix()
            tar.add(str(path), arcname=arcname, recursive=False)


def _integrity_codes(assessment: object) -> list[str]:
    """Collect the ACEF-NNN codes from an assessment's structural errors."""
    errors = getattr(assessment, "structural_errors", [])
    return [str(d.get("code", "")) for d in errors]


class TestValidateArchiveIntegrity:
    """``acef.validate`` on a ``.tar.gz`` must verify the RAW archive bytes."""

    def test_archive_missing_merkle_reports_acef011(self, minimal_package: Package, tmp_dir: Path) -> None:
        """ARCHIVE with ``hashes/merkle-tree.json`` stripped → FATAL ACEF-011.

        RED proof: before the root fix the public ``validate`` round-trips the
        archive through ``load`` → ``export``, regenerating the stripped Merkle
        file, so ``structural_errors`` carries NO ACEF-011 — the tampering is
        healed at the public API. After the fix it is PRESENT and FATAL at
        ``/hashes/merkle-tree.json``.
        """
        bundle_dir = tmp_dir / "lib-no-merkle.acef"
        minimal_package.export(str(bundle_dir))
        assert (bundle_dir / "hashes" / "merkle-tree.json").exists()

        archive = tmp_dir / "lib-no-merkle.acef.tar.gz"
        _build_raw_archive(bundle_dir, archive, skip={"hashes/merkle-tree.json"})

        assessment = acef.validate(str(archive))

        merkle_diags = [
            d
            for d in assessment.structural_errors
            if d.get("code") == "ACEF-011" and d.get("path") == "/hashes/merkle-tree.json"
        ]
        assert merkle_diags, (
            "public acef.validate healed the stripped merkle-tree.json instead of "
            f"reporting ACEF-011; codes seen: {_integrity_codes(assessment)}"
        )
        assert merkle_diags[0].get("severity") == "fatal"

    def test_archive_content_hash_mismatch_reports_acef010(self, minimal_package: Package, tmp_dir: Path) -> None:
        """ARCHIVE whose manifest bytes are tampered (still valid JSON, hash no
        longer matches the recorded content hash) → FATAL ACEF-010.

        RED proof: before the root fix ``load`` → ``export`` recomputes the
        content hashes from the tampered bytes, so the recorded and recomputed
        hashes agree — ACEF-010 NEVER fires. After the fix the raw archive bytes
        are verified as-received and the mismatch is surfaced.
        """
        bundle_dir = tmp_dir / "lib-tampered-field.acef"
        minimal_package.export(str(bundle_dir))

        manifest_path = bundle_dir / "acef-manifest.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        # Tamper a field WITHOUT touching hashes/* — still valid JSON, but its
        # SHA-256 no longer matches the recorded content hash.
        manifest.setdefault("metadata", {})["x-tamper-marker"] = "mutated-after-hash"
        manifest_path.write_text(json.dumps(manifest), encoding="utf-8")

        archive = tmp_dir / "lib-tampered-field.acef.tar.gz"
        _build_raw_archive(bundle_dir, archive)

        assessment = acef.validate(str(archive))

        codes = _integrity_codes(assessment)
        assert "ACEF-010" in codes, (
            f"public acef.validate healed the content-hash mismatch instead of reporting ACEF-010; codes seen: {codes}"
        )

    def test_healthy_archive_no_integrity_errors(self, minimal_package: Package, tmp_dir: Path) -> None:
        """A healthy, untampered archive → ``acef.validate`` emits NO integrity
        codes (ACEF-010/ACEF-011). Guards against a false positive from
        verifying the raw archive bytes."""
        bundle_dir = tmp_dir / "lib-healthy.acef"
        minimal_package.export(str(bundle_dir))

        archive = tmp_dir / "lib-healthy.acef.tar.gz"
        _build_raw_archive(bundle_dir, archive)

        assessment = acef.validate(str(archive))

        codes = _integrity_codes(assessment)
        assert "ACEF-011" not in codes, codes
        assert "ACEF-010" not in codes, codes

    def test_archive_and_directory_agree(self, minimal_package: Package, tmp_dir: Path) -> None:
        """A healthy archive and the equivalent directory bundle produce the same
        integrity verdict (both clean) through ``acef.validate`` — archive input
        is no longer a privileged "self-healing" path."""
        bundle_dir = tmp_dir / "lib-parity.acef"
        minimal_package.export(str(bundle_dir))

        archive = tmp_dir / "lib-parity.acef.tar.gz"
        _build_raw_archive(bundle_dir, archive)

        dir_assessment = acef.validate(str(bundle_dir))
        archive_assessment = acef.validate(str(archive))

        dir_integrity = {c for c in _integrity_codes(dir_assessment) if c in {"ACEF-010", "ACEF-011"}}
        archive_integrity = {c for c in _integrity_codes(archive_assessment) if c in {"ACEF-010", "ACEF-011"}}
        assert dir_integrity == archive_integrity == set()

    def test_directory_input_unchanged(self, minimal_package: Package, tmp_dir: Path) -> None:
        """Directory-input behavior is preserved exactly: a valid directory
        bundle validates and yields a well-formed AssessmentBundle."""
        bundle_dir = tmp_dir / "lib-dir.acef"
        minimal_package.export(str(bundle_dir))

        assessment = acef.validate(str(bundle_dir))

        assert assessment.assessment_id.startswith("urn:acef:asx:")
        assert assessment.evidence_bundle_ref.package_id
        codes = _integrity_codes(assessment)
        assert "ACEF-011" not in codes, codes
        assert "ACEF-010" not in codes, codes
